spring:
  datasource:
    url: jdbc:mysql:///stu_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: stu_service
  registry:
    address: zookeeper://152.136.157.169:2181
  #协议
  protocol:
    name: dubbo
    #-1表示默认一个不冲突的分配端口
    port: -1
  consumer:
    check: false
